CREATE TABLE DOCUMENT (
    ID               VARCHAR2(32)   NOT NULL,
    NAME             VARCHAR2(255)  NOT NULL,
    CONTENT_TYPE     VARCHAR2(100)  NOT NULL,
    STATUS           VARCHAR2(20)   NOT NULL,
    IDEMPOTENCY_KEY  VARCHAR2(255),
    CREATED_AT       TIMESTAMP      NOT NULL,
    UPDATED_AT       TIMESTAMP      NOT NULL,

    CONSTRAINT PK_DOCUMENT
        PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX UX_DOCUMENT_IDEMPOTENCY_KEY
    ON DOCUMENT (IDEMPOTENCY_KEY);

CREATE TABLE DOCUMENT_EVENT (
    ID              VARCHAR2(64)   NOT NULL,
    DOCUMENT_ID     VARCHAR2(32)   NOT NULL,
    EVENT_TYPE      VARCHAR2(50)   NOT NULL,
    OCCURRED_AT     TIMESTAMP      NOT NULL,
    CORRELATION_ID  VARCHAR2(255),

    CONSTRAINT PK_DOCUMENT_EVENT
        PRIMARY KEY (ID),

    CONSTRAINT FK_DOCUMENT_EVENT_DOCUMENT
        FOREIGN KEY (DOCUMENT_ID)
        REFERENCES DOCUMENT(ID)
);

CREATE INDEX IX_DOCUMENT_EVENT_DOCUMENT_ID
    ON DOCUMENT_EVENT (DOCUMENT_ID);